apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: task-api-ns
  labels:
    app: postgres
    tier: database
spec:
  selector:
    matchLabels:
      app: postgres
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
      - image: postgres:11
        name: postgres
        env:        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: task-api-db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: task-api-db-secrets
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: task-api-db-cm
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/posgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim