apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: task-api-ns
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: database
  clusterIP: None