apiVersion: v1
kind: Service
metadata:
  labels:
    run: task-api-pod
  name: task-api-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: task-api-pod
  type: LoadBalancer