apiVersion: v1
kind: Pod
metadata:
  labels:
    run: task-api-cm-pod
  name: task-api-cm-pod
spec:
  containers:
    - name: task-api-cm-pod
      image: rmontesleo/springboot-todo-h2-api-k8s:v1    
      env:
        - name: user_data
          valueFrom:
            configMapKeyRef:
              name: task-api-cm
              key: user_data
        - name: user_name
          valueFrom:
            configMapKeyRef:
              name: task-api-cm
              key: user_name
    