apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-api
  name: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: springboot-todo-h2-api-k8s 
        image: rmontesleo/springboot-todo-h2-api-k8s:v1        
        ports:
        - containerPort: 8080